name: Silicon Labs firmware build

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yaml
      - .github/workflows/silabs-firmware-build.yaml
      - EmberZNet/**
      - OpenThreadRCP/**
      - RCPMultiPAN/**
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  sdk_version: 4.1.5

jobs:
  build-container:
    name: Create build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      sdk_version: ${{ env.sdk_version }}
      ot_version: 2.1.5.0
      ezsp_version: 7.1.5.0
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Build and Push
        uses: docker/build-push-action@v3.3.0
        with:
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.repository }}:${{ env.sdk_version }}
          cache-from: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          cache-to: ghcr.io/${{ github.repository }}:cache-${{ env.sdk_version }}
          push: true
          build-args:
            "GECKO_SDK_VERSION=v${{ env.sdk_version }}"

  ezsp-firmware-build:
    name: EmberZNet NCP
    needs: build-container
    strategy:
      matrix:
        target: [zbdonglee, zbdonglee-none, zb-gw04-1v2]
        baudrate: [115200, 230400]
        include:
          - device: EFR32MG21A020F768IM32
          - target: zbdonglee
            patchpath: "EmberZNet/ZBDongleE"
          - target: zbdonglee-none
            patchpath: "EmberZNet/ZBDongleE-none"
          - target: zb-gw04-1v2
            patchpath: "EmberZNet/ZB-GW04-1v2"
          - target: yellow
            device: MGM210PA32JIA
            components: simple_led:board_activity,zigbee_token_interface
            patchpath: "EmberZNet/Yellow"
            baudrate: 115200
          - target: skyconnect
            device: EFR32MG21A020F512IM32
            components: zigbee_token_interface
            patchpath: "EmberZNet/SkyConnect"
            baudrate: 115200
        exclude:
          - target: zbdonglee-none
            baudrate: 230400
    uses: ./.github/workflows/silabs-firmware-build.yaml
    with:
      firmware_name: ncp-uart-hw-v${{ needs.build-container.outputs.ezsp_version}}-${{ matrix.target }}-${{ matrix.baudrate }}
      project_file: "/gecko_sdk/protocol/zigbee/app/ncp/sample-app/ncp-uart-hw/ncp-uart-hw.slcp"
      project_name: "ncp-uart-hw"
      device: ${{ matrix.device }}
      components: ${{ matrix.components }}
      configuration:  |
        SL_IOSTREAM_USART_VCOM_RX_BUFFER_SIZE:64,
        EMBER_APS_UNICAST_MESSAGE_COUNT:20,
        EMBER_NEIGHBOR_TABLE_SIZE:26,
        EMBER_SOURCE_ROUTE_TABLE_SIZE:200,
      patchpath: ${{ matrix.patchpath }}
      extra_c_defs: "'-DEMBER_ADDRESS_TABLE_SIZE=16' '-DEMBER_MULTICAST_TABLE_SIZE=16'"
      sdk_version: ${{ needs.build-container.outputs.sdk_version}}
      metadata_fw_type: "ncp-uart-hw"
      baudrate: ${{ matrix.baudrate }}
      metadata_extra: "{ \"ezsp_version\": \"${{ needs.build-container.outputs.ezsp_version}}\" }"

  collect_artifacts:
    name: download and publish all artifacts
    runs-on: ubuntu-latest
    needs: [ezsp-firmware-build]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/download-artifact@v3
        with:
          path: firmware_builds
      - name: Reorganise artifact structure
        run: |
          mv */*.gbl .
          rm -rf *cp-uart-*/ ot-rcp*/
          find ./ -maxdepth 1 -name "*zbdongle*.gbl" ! -name "*460*" | while read f
          do
              new=$(echo $f | sed "s/zbdonglee/zb-gw04-1v1/")
              cp $f $new
          done

          targets="skyconnect yellow zb-gw04-1v1 zb-gw04-1v2 zbdonglee"
          for t in $targets; do
                  mkdir -p $t
                  find . -maxdepth 1 -type f -name "*$t*" -exec mv {} "$t" \;
          done
        working-directory: firmware_builds
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update firmware builds
          file_pattern: firmware_builds/**.gbl
